### ISSUE TITLE
[Request] Option to have a whitelist file instead of a blacklist file

### ISSUE THREAD

**Issue by justastranger** [BepInEx/BepInEx.MultiFolderLoader#2]
The game Cultist Simulator keeps track of which of its mods are enabled in a simple text file, with one folder name per line. Using this plug-in, I can load plugins and mods from the same folders and potentially distribute the mods over the Workshop. If it became possible to use the in-game mod manager to manage the plugins, it would simplify the process a lot for end users.

**Comment by ghorsington** [comment]
Should now be available as `enabledModsListPath` config option in 1.2
