### ISSUE TITLE
[Request] Use `Environment.ExpandEnvironmentVariables` to parse config entries

### ISSUE THREAD

**Issue by justastranger** [BepInEx/BepInEx.MultiFolderLoader#3]
Currently, only a raw, direct path works in the config. If environment variables like `%AppData%` were supported, a single config file could be used for any player of a game where plugins would be loaded from inside the AppData folder. Otherwise, the config values would have to vary depending on the current username being used and be manually filled in.

It would also remove the only barrier that I can see regarding a pre-configured BepInEx installer for the game I'm working with.

**Comment by ghorsington** [comment]
Implemented in 04a538685bbe307feab9d9bd04985b26e911a734

**Comment by justastranger** [comment]
Thank you very much :)
